name: build_wintools
on:
  push: {tags:  ['v*'] } # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request: 

permissions:
  contents: write
  
jobs:
  build_win_libzip:
    runs-on: windows-2019
    steps:
    - name: pull and init
      uses: actions/checkout@v3
      with: {submodules: true}
    
    - name: add msbuild to path
      uses: microsoft/setup-msbuild@v1.1
    
    - name: build target
      run: script/build_win_msvc.bat
    
    - name: upload release
      uses: ncipollo/release-action@v1
      if: github.event_name == 'push'
      with:
        artifacts: "build/libzip32.dll,build/libzip64.dll"
        allowUpdates: "true"
        token: ${{ secrets.GITHUB_TOKEN }}

  build_linux_libzip:
    runs-on: ubuntu-20.04
    steps:
    - name: pull and init
      uses: actions/checkout@v3
      with: {submodules: true}
    
    - name: prepare enviroment
      run: |
        sudo apt-get -y install gcc-multilib
        sudo apt-get -y install crossbuild-essential-i386

    - name: build target
      run: script/build_linux_gcc.sh
    
    - name: upload release
      uses: ncipollo/release-action@v1
      if: github.event_name == 'push'
      with:
        artifacts: "build/libzip32.so,build/libzip64.so"
        allowUpdates: "true"
        token: ${{ secrets.GITHUB_TOKEN }}