name: test_tools
on:
  push: {tags:  ['v*'] } # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request: 

permissions:
  contents: write
  
jobs:
  test_win_libzip:
    runs-on: windows-2019
    steps:
    - name: pull and init
      uses: actions/checkout@v3
      with: {submodules: true}
    
    - name: add msbuild to path
      uses: microsoft/setup-msbuild@v1.1
    
    - name: test target
      run: script/test_win_msvc.bat

  test_linux_libzip:
    runs-on: ubuntu-22.04
    steps:
    - name: pull and init
      uses: actions/checkout@v3
      with: {submodules: true}
    
    - name: prepare enviroment
      run: |
        sudo apt-get -y update
        sudo apt-get -y install gcc-multilib
        sudo apt-get -y install crossbuild-essential-i386

    - name: test target
      run: script/test_linux_gcc.sh